ALTER TABLE uniqueid DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE personalization DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE readingcontrol DROP	CONSTRAINT PRIMARY KEY;
ALTER TABLE subscribe DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE model_contact DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE model DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE favorit DROP CONSTRAINT PRIMARY KEY;

ALTER TABLE calendarjournal DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE calendarCategory DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE calendarjournalattendee DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE calendarjournalcategory DROP CONSTRAINT PRIMARY KEY;

ALTER TABLE calendartodo DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE calendartodoattendee DROP CONSTRAINT PRIMARY KEY;

ALTER TABLE st_formeditor_formedited DROP CONSTRAINT PRIMARY KEY;
ALTER TABLE st_formeditor_formediteddata DROP CONSTRAINT PRIMARY KEY;

ALTER TABLE sb_agenda_import_settings DROP CONSTRAINT PRIMARY KEY;



